spring:
  application:
    name: problem-service

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true