#!/usr/bin/env node
/* global console, process */
/*
 * Modified for Cherry OJ on 2026-08-28.
 * Deterministically generates the Web-owned stable CSS entrypoint from the
 * local Foundation, theme contract, and theme manifest.
 * See ../NOTICE.md and ../LICENSE.open-design.
 */

import { lstat, readFile, realpath, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const scriptFile = fileURLToPath(import.meta.url);
export const rootDir = path.resolve(path.dirname(scriptFile), "..");
const rootRealPath = await realpath(rootDir);

function isInsideRoot(relativePath) {
  return relativePath !== ".." && !relativePath.startsWith(`..${path.sep}`) && !path.isAbsolute(relativePath);
}

export async function resolveInputPath(relativePath) {
  if (typeof relativePath !== "string" || relativePath.length === 0 || path.isAbsolute(relativePath)) {
    throw new Error(`design-system input must be a non-empty relative path: ${relativePath}`);
  }

  const lexicalPath = path.resolve(rootDir, relativePath);
  if (!isInsideRoot(path.relative(rootDir, lexicalPath))) {
    throw new Error(`design-system input escapes the package root: ${relativePath}`);
  }

  const metadata = await lstat(lexicalPath);
  if (metadata.isSymbolicLink()) {
    throw new Error(`design-system input must not be a symbolic link: ${relativePath}`);
  }

  const inputRealPath = await realpath(lexicalPath);
  if (!isInsideRoot(path.relative(rootRealPath, inputRealPath))) {
    throw new Error(`design-system input resolves outside the package root: ${relativePath}`);
  }
  return inputRealPath;
}

async function resolveOutputPath(relativePath) {
  if (typeof relativePath !== "string" || relativePath.length === 0 || path.isAbsolute(relativePath)) {
    throw new Error(`design-system output must be a non-empty relative path: ${relativePath}`);
  }

  const lexicalPath = path.resolve(rootDir, relativePath);
  if (!isInsideRoot(path.relative(rootDir, lexicalPath))) {
    throw new Error(`design-system output escapes the package root: ${relativePath}`);
  }

  let metadata;
  try {
    metadata = await lstat(lexicalPath);
  } catch (error) {
    if (error?.code !== "ENOENT") throw error;
    const parentRealPath = await realpath(path.dirname(lexicalPath));
    if (!isInsideRoot(path.relative(rootRealPath, parentRealPath)) && parentRealPath !== rootRealPath) {
      throw new Error(`design-system output parent resolves outside the package root: ${relativePath}`);
    }
    return lexicalPath;
  }

  if (metadata.isSymbolicLink()) {
    throw new Error(`design-system output must not be a symbolic link: ${relativePath}`);
  }
  if (!metadata.isFile()) {
    throw new Error(`design-system output must be a regular file: ${relativePath}`);
  }

  const outputRealPath = await realpath(lexicalPath);
  if (!isInsideRoot(path.relative(rootRealPath, outputRealPath))) {
    throw new Error(`design-system output resolves outside the package root: ${relativePath}`);
  }
  return outputRealPath;
}

async function readText(relativePath) {
  return readFile(await resolveInputPath(relativePath), "utf8");
}

async function readJson(relativePath) {
  return JSON.parse(await readText(relativePath));
}

export function parseCustomProperties(css) {
  const tokens = {};
  const declaration = /(--[a-zA-Z0-9-]+)\s*:\s*([^;]+);/g;
  for (const match of css.matchAll(declaration)) {
    tokens[match[1]] = match[2].replace(/\s+/g, " ").trim();
  }
  return tokens;
}

function generatedCss(themeManifest) {
  const imports = ["tokens.foundation.css", ...themeManifest.themes.map((theme) => theme.file)]
    .map((file) => `@import "./${file}";`)
    .join("\n");

  return `/*
 * GENERATED by tools/build.mjs. Do not edit directly.
 * Modified for Cherry OJ on 2026-08-27.
 * Derived from the OpenDesign linear-app fixture; Cherry changes include a
 * semantic theme contract, Cherry branding, OJ states, and pure-white.
 * See NOTICE.md and LICENSE.open-design in this directory.
 */

${imports}
`;
}

function validateInputs(themeManifest, contract) {
  if (themeManifest.schemaVersion !== 1 || contract.schemaVersion !== 1) {
    throw new Error("theme manifest and contract schemaVersion must both be 1");
  }
  if (!Array.isArray(themeManifest.themes) || themeManifest.themes.length === 0) {
    throw new Error("themes.manifest.json must register at least one theme");
  }
  if (themeManifest.selectorAttribute !== "data-theme") {
    throw new Error("themes.manifest.json selectorAttribute must be data-theme");
  }
  if (themeManifest.followSystemByDefault !== false) {
    throw new Error("themes.manifest.json followSystemByDefault must be false");
  }

  const ids = new Set();
  const files = new Set();
  for (const theme of themeManifest.themes) {
    if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(theme.id)) throw new Error(`invalid theme id: ${theme.id}`);
    if (theme.file !== `themes/${theme.id}.css`) throw new Error(`${theme.id} file must be themes/${theme.id}.css`);
    if (!["dark", "light"].includes(theme.colorScheme)) throw new Error(`${theme.id} has invalid colorScheme`);
    if (typeof theme.label !== "string" || theme.label.trim().length === 0) {
      throw new Error(`${theme.id} label must be non-empty`);
    }
    if (typeof theme.provenance !== "string" || theme.provenance.trim().length === 0) {
      throw new Error(`${theme.id} provenance must be non-empty`);
    }
    if (!Number.isInteger(theme.version) || theme.version < 1) {
      throw new Error(`${theme.id} version must be a positive integer`);
    }
    if (ids.has(theme.id) || files.has(theme.file)) throw new Error(`duplicate theme id or file: ${theme.id}`);
    ids.add(theme.id);
    files.add(theme.file);
  }
  if (!ids.has(themeManifest.defaultTheme) || !ids.has(themeManifest.fallbackTheme)) {
    throw new Error("default and fallback theme ids must be registered");
  }
  if (themeManifest.themes[0].id !== themeManifest.defaultTheme) {
    throw new Error("default theme must be the first registered theme");
  }
}

export async function generateOutputs() {
  const themeManifest = await readJson("themes.manifest.json");
  const contract = await readJson("theme-contract.json");
  validateInputs(themeManifest, contract);

  await resolveInputPath("tokens.foundation.css");
  for (const theme of themeManifest.themes) await resolveInputPath(theme.file);

  return { "tokens.css": generatedCss(themeManifest) };
}

async function run() {
  const argumentsList = process.argv.slice(2);
  if (argumentsList.length > 1 || (argumentsList.length === 1 && argumentsList[0] !== "--check")) {
    throw new Error("build.mjs accepts only the optional --check argument");
  }

  const checkOnly = argumentsList[0] === "--check";
  const outputs = await generateOutputs();
  const stale = [];

  for (const [relativePath, expected] of Object.entries(outputs)) {
    const absolutePath = await resolveOutputPath(relativePath);
    if (checkOnly) {
      let actual = "";
      try {
        actual = await readFile(absolutePath, "utf8");
      } catch (error) {
        if (error?.code !== "ENOENT") throw error;
      }
      if (actual !== expected) stale.push(relativePath);
      continue;
    }

    await writeFile(absolutePath, expected, "utf8");
    console.log(`generated ${relativePath}`);
  }

  if (stale.length > 0) {
    throw new Error(`generated output is stale: ${stale.join(", ")}; run node tools/build.mjs`);
  }
  if (checkOnly) console.log("generated outputs are current");
}

const invokedFile = process.argv[1] ? path.resolve(process.argv[1]) : "";
if (invokedFile === scriptFile) {
  run().catch((error) => {
    console.error(error.message);
    process.exitCode = 1;
  });
}
