/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteForbiddenRouteImport } from './routes/_site.forbidden'
import { Route as SiteLoginRouteImport } from './routes/_site.login'
import { Route as SiteProblemsRouteImport } from './routes/_site.problems'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminDashboradRouteImport } from './routes/admin.dashborad'
import { Route as AdminProblemsRouteImport } from './routes/admin.problems'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as SiteAccountPasswordRouteImport } from './routes/_site.account.password'
import { Route as SiteProblemsIndexRouteImport } from './routes/_site.problems.index'
import { Route as SiteProblemsSlugRouteImport } from './routes/_site.problems.$slug'
import { Route as AdminProblemsIndexRouteImport } from './routes/admin.problems.index'
import { Route as AdminProblemsProblemIdVersionsVersionIdRouteImport } from './routes/admin.problems.$problemId.versions.$versionId'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteForbiddenRoute = SiteForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => SiteRoute,
} as any)
const SiteLoginRoute = SiteLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => SiteRoute,
} as any)
const SiteProblemsRoute = SiteProblemsRouteImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => SiteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboradRoute = AdminDashboradRouteImport.update({
  id: '/dashborad',
  path: '/dashborad',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProblemsRoute = AdminProblemsRouteImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const SiteAccountPasswordRoute = SiteAccountPasswordRouteImport.update({
  id: '/account/password',
  path: '/account/password',
  getParentRoute: () => SiteRoute,
} as any)
const SiteProblemsIndexRoute = SiteProblemsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteProblemsRoute,
} as any)
const SiteProblemsSlugRoute = SiteProblemsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SiteProblemsRoute,
} as any)
const AdminProblemsIndexRoute = AdminProblemsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminProblemsRoute,
} as any)
const AdminProblemsProblemIdVersionsVersionIdRoute =
  AdminProblemsProblemIdVersionsVersionIdRouteImport.update({
    id: '/$problemId/versions/$versionId',
    path: '/$problemId/versions/$versionId',
    getParentRoute: () => AdminProblemsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forbidden': typeof SiteForbiddenRoute
  '/login': typeof SiteLoginRoute
  '/problems': typeof SiteProblemsRouteWithChildren
  '/admin/dashborad': typeof AdminDashboradRoute
  '/admin/problems': typeof AdminProblemsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/account/password': typeof SiteAccountPasswordRoute
  '/problems/$slug': typeof SiteProblemsSlugRoute
  '/problems/': typeof SiteProblemsIndexRoute
  '/admin/problems/': typeof AdminProblemsIndexRoute
  '/admin/problems/$problemId/versions/$versionId': typeof AdminProblemsProblemIdVersionsVersionIdRoute
}
export interface FileRoutesByTo {
  '/forbidden': typeof SiteForbiddenRoute
  '/login': typeof SiteLoginRoute
  '/admin/dashborad': typeof AdminDashboradRoute
  '/admin/users': typeof AdminUsersRoute
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminIndexRoute
  '/account/password': typeof SiteAccountPasswordRoute
  '/problems/$slug': typeof SiteProblemsSlugRoute
  '/problems': typeof SiteProblemsIndexRoute
  '/admin/problems': typeof AdminProblemsIndexRoute
  '/admin/problems/$problemId/versions/$versionId': typeof AdminProblemsProblemIdVersionsVersionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_site/forbidden': typeof SiteForbiddenRoute
  '/_site/login': typeof SiteLoginRoute
  '/_site/problems': typeof SiteProblemsRouteWithChildren
  '/admin/dashborad': typeof AdminDashboradRoute
  '/admin/problems': typeof AdminProblemsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/_site/': typeof SiteIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_site/account/password': typeof SiteAccountPasswordRoute
  '/_site/problems/$slug': typeof SiteProblemsSlugRoute
  '/_site/problems/': typeof SiteProblemsIndexRoute
  '/admin/problems/': typeof AdminProblemsIndexRoute
  '/admin/problems/$problemId/versions/$versionId': typeof AdminProblemsProblemIdVersionsVersionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forbidden'
    | '/login'
    | '/problems'
    | '/admin/dashborad'
    | '/admin/problems'
    | '/admin/users'
    | '/admin/'
    | '/account/password'
    | '/problems/$slug'
    | '/problems/'
    | '/admin/problems/'
    | '/admin/problems/$problemId/versions/$versionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forbidden'
    | '/login'
    | '/admin/dashborad'
    | '/admin/users'
    | '/'
    | '/admin'
    | '/account/password'
    | '/problems/$slug'
    | '/problems'
    | '/admin/problems'
    | '/admin/problems/$problemId/versions/$versionId'
  id:
    | '__root__'
    | '/_site'
    | '/admin'
    | '/_site/forbidden'
    | '/_site/login'
    | '/_site/problems'
    | '/admin/dashborad'
    | '/admin/problems'
    | '/admin/users'
    | '/_site/'
    | '/admin/'
    | '/_site/account/password'
    | '/_site/problems/$slug'
    | '/_site/problems/'
    | '/admin/problems/'
    | '/admin/problems/$problemId/versions/$versionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/forbidden': {
      id: '/_site/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof SiteForbiddenRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/login': {
      id: '/_site/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof SiteLoginRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/problems': {
      id: '/_site/problems'
      path: '/problems'
      fullPath: '/problems'
      preLoaderRoute: typeof SiteProblemsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashborad': {
      id: '/admin/dashborad'
      path: '/dashborad'
      fullPath: '/admin/dashborad'
      preLoaderRoute: typeof AdminDashboradRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/problems': {
      id: '/admin/problems'
      path: '/problems'
      fullPath: '/admin/problems'
      preLoaderRoute: typeof AdminProblemsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_site/account/password': {
      id: '/_site/account/password'
      path: '/account/password'
      fullPath: '/account/password'
      preLoaderRoute: typeof SiteAccountPasswordRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/problems/': {
      id: '/_site/problems/'
      path: '/'
      fullPath: '/problems/'
      preLoaderRoute: typeof SiteProblemsIndexRouteImport
      parentRoute: typeof SiteProblemsRoute
    }
    '/_site/problems/$slug': {
      id: '/_site/problems/$slug'
      path: '/$slug'
      fullPath: '/problems/$slug'
      preLoaderRoute: typeof SiteProblemsSlugRouteImport
      parentRoute: typeof SiteProblemsRoute
    }
    '/admin/problems/': {
      id: '/admin/problems/'
      path: '/'
      fullPath: '/admin/problems/'
      preLoaderRoute: typeof AdminProblemsIndexRouteImport
      parentRoute: typeof AdminProblemsRoute
    }
    '/admin/problems/$problemId/versions/$versionId': {
      id: '/admin/problems/$problemId/versions/$versionId'
      path: '/$problemId/versions/$versionId'
      fullPath: '/admin/problems/$problemId/versions/$versionId'
      preLoaderRoute: typeof AdminProblemsProblemIdVersionsVersionIdRouteImport
      parentRoute: typeof AdminProblemsRoute
    }
  }
}

interface SiteProblemsRouteChildren {
  SiteProblemsSlugRoute: typeof SiteProblemsSlugRoute
  SiteProblemsIndexRoute: typeof SiteProblemsIndexRoute
}

const SiteProblemsRouteChildren: SiteProblemsRouteChildren = {
  SiteProblemsSlugRoute: SiteProblemsSlugRoute,
  SiteProblemsIndexRoute: SiteProblemsIndexRoute,
}

const SiteProblemsRouteWithChildren = SiteProblemsRoute._addFileChildren(
  SiteProblemsRouteChildren,
)

interface SiteRouteChildren {
  SiteForbiddenRoute: typeof SiteForbiddenRoute
  SiteLoginRoute: typeof SiteLoginRoute
  SiteProblemsRoute: typeof SiteProblemsRouteWithChildren
  SiteIndexRoute: typeof SiteIndexRoute
  SiteAccountPasswordRoute: typeof SiteAccountPasswordRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteForbiddenRoute: SiteForbiddenRoute,
  SiteLoginRoute: SiteLoginRoute,
  SiteProblemsRoute: SiteProblemsRouteWithChildren,
  SiteIndexRoute: SiteIndexRoute,
  SiteAccountPasswordRoute: SiteAccountPasswordRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

interface AdminProblemsRouteChildren {
  AdminProblemsIndexRoute: typeof AdminProblemsIndexRoute
  AdminProblemsProblemIdVersionsVersionIdRoute: typeof AdminProblemsProblemIdVersionsVersionIdRoute
}

const AdminProblemsRouteChildren: AdminProblemsRouteChildren = {
  AdminProblemsIndexRoute: AdminProblemsIndexRoute,
  AdminProblemsProblemIdVersionsVersionIdRoute:
    AdminProblemsProblemIdVersionsVersionIdRoute,
}

const AdminProblemsRouteWithChildren = AdminProblemsRoute._addFileChildren(
  AdminProblemsRouteChildren,
)

interface AdminRouteChildren {
  AdminDashboradRoute: typeof AdminDashboradRoute
  AdminProblemsRoute: typeof AdminProblemsRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboradRoute: AdminDashboradRoute,
  AdminProblemsRoute: AdminProblemsRouteWithChildren,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
