CREATE TABLE judge_environment (
    id BINARY(16) NOT NULL,
    name VARCHAR(128) NOT NULL,
    fingerprint VARCHAR(256) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    active_slot TINYINT GENERATED ALWAYS AS (CASE WHEN status = 'ACTIVE' THEN 1 ELSE NULL END) STORED,
    architecture VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    cpu_model VARCHAR(256) NOT NULL,
    os_version VARCHAR(128) NOT NULL,
    kernel_version VARCHAR(128) NOT NULL,
    judge_version VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    sandbox_version VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    config_digest VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    endpoint_ref VARCHAR(512) COLLATE utf8mb4_bin NOT NULL,
    created_at DATETIME(6) NOT NULL,
    activated_at DATETIME(6) NULL,
    retired_at DATETIME(6) NULL,
    row_version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT uq_judge_environment_fingerprint UNIQUE (fingerprint),
    CONSTRAINT uq_judge_environment_one_active UNIQUE (active_slot),
    KEY idx_judge_environment_status_created (status, created_at, id),
    CONSTRAINT ck_judge_environment_status CHECK (status IN ('REGISTERED', 'ACTIVE', 'RETIRED')),
    CONSTRAINT ck_judge_environment_times CHECK ((status <> 'ACTIVE' OR (activated_at IS NOT NULL AND retired_at IS NULL)) AND (status <> 'RETIRED' OR retired_at IS NOT NULL)),
    CONSTRAINT ck_judge_environment_row_version CHECK (row_version >= 0)
) ENGINE = InnoDB;

CREATE TABLE judge_environment_language (
    judge_environment_id BINARY(16) NOT NULL,
    language_id VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    toolchain_version VARCHAR(256) NOT NULL,
    language_config_digest VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    enabled BOOLEAN NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    row_version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (judge_environment_id, language_id),
    KEY idx_environment_language_enabled (language_id, enabled, judge_environment_id),
    CONSTRAINT fk_environment_language_environment FOREIGN KEY (judge_environment_id) REFERENCES judge_environment (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_environment_language_id CHECK (REGEXP_LIKE(language_id, '^[a-z][a-z0-9-]{0,31}$', 'c')),
    CONSTRAINT ck_environment_language_enabled CHECK (enabled IN (0, 1)),
    CONSTRAINT ck_environment_language_row_version CHECK (row_version >= 0),
    CONSTRAINT ck_environment_language_time CHECK (updated_at >= created_at)
) ENGINE = InnoDB;

CREATE TABLE test_data_deployment (
    test_data_version_id BINARY(16) NOT NULL,
    judge_environment_id BINARY(16) NOT NULL,
    expected_sha256 BINARY(32) NOT NULL,
    status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    deployed_sha256 BINARY(32) NULL,
    deployed_at DATETIME(6) NULL,
    error_message TEXT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    row_version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (test_data_version_id, judge_environment_id),
    KEY idx_deployment_environment_status (judge_environment_id, status, updated_at),
    CONSTRAINT fk_deployment_environment FOREIGN KEY (judge_environment_id) REFERENCES judge_environment (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_deployment_status CHECK (status IN ('PENDING', 'DEPLOYING', 'READY', 'FAILED')),
    CONSTRAINT ck_deployment_ready CHECK (status <> 'READY' OR (deployed_sha256 IS NOT NULL AND deployed_sha256 = expected_sha256 AND deployed_at IS NOT NULL AND error_message IS NULL)),
    CONSTRAINT ck_deployment_failed CHECK (status <> 'FAILED' OR error_message IS NOT NULL),
    CONSTRAINT ck_deployment_error_length CHECK (error_message IS NULL OR CHAR_LENGTH(error_message) <= 8192),
    CONSTRAINT ck_deployment_row_version CHECK (row_version >= 0),
    CONSTRAINT ck_deployment_time CHECK (updated_at >= created_at)
) ENGINE = InnoDB;

CREATE TABLE language_calibration (
    id BINARY(16) NOT NULL,
    problem_version_id BINARY(16) NOT NULL,
    language_id VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    judge_environment_id BINARY(16) NOT NULL,
    status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    valid_slot TINYINT GENERATED ALWAYS AS (CASE WHEN status = 'VALID' THEN 1 ELSE NULL END) STORED,
    source_type VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    cpu_ns BIGINT NULL,
    memory_bytes BIGINT NULL,
    clock_ns BIGINT NULL,
    benchmark_summary_json JSON NULL,
    approved_by BINARY(16) NULL,
    approved_at DATETIME(6) NULL,
    supersedes_id BINARY(16) NULL,
    error_message TEXT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    row_version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT uq_calibration_one_valid UNIQUE (problem_version_id, language_id, judge_environment_id, valid_slot),
    KEY idx_calibration_resolve (problem_version_id, language_id, judge_environment_id, status),
    KEY idx_calibration_environment_status (judge_environment_id, status, updated_at),
    KEY idx_calibration_supersedes (supersedes_id),
    CONSTRAINT fk_calibration_environment FOREIGN KEY (judge_environment_id) REFERENCES judge_environment (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_calibration_supersedes FOREIGN KEY (supersedes_id) REFERENCES language_calibration (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_calibration_language CHECK (REGEXP_LIKE(language_id, '^[a-z][a-z0-9-]{0,31}$', 'c')),
    CONSTRAINT ck_calibration_status CHECK (status IN ('DRAFT', 'RUNNING', 'VALID', 'FAILED', 'SUPERSEDED')),
    CONSTRAINT ck_calibration_source CHECK (source_type IN ('MANUAL', 'BENCHMARK')),
    CONSTRAINT ck_calibration_limits CHECK ((cpu_ns IS NULL OR cpu_ns > 0) AND (memory_bytes IS NULL OR memory_bytes > 0) AND (clock_ns IS NULL OR clock_ns > 0)),
    CONSTRAINT ck_calibration_valid CHECK (status <> 'VALID' OR (cpu_ns IS NOT NULL AND memory_bytes IS NOT NULL AND approved_by IS NOT NULL AND approved_at IS NOT NULL AND error_message IS NULL)),
    CONSTRAINT ck_calibration_failed CHECK (status <> 'FAILED' OR error_message IS NOT NULL),
    CONSTRAINT ck_calibration_benchmark CHECK (benchmark_summary_json IS NULL OR JSON_TYPE(benchmark_summary_json) = 'OBJECT'),
    CONSTRAINT ck_calibration_error_length CHECK (error_message IS NULL OR CHAR_LENGTH(error_message) <= 8192),
    CONSTRAINT ck_calibration_row_version CHECK (row_version >= 0),
    CONSTRAINT ck_calibration_time CHECK (updated_at >= created_at)
) ENGINE = InnoDB;

CREATE TABLE judging_audit_event (
    id BINARY(16) NOT NULL,
    aggregate_type VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    aggregate_id BINARY(16) NOT NULL,
    actor_user_id BINARY(16) NULL,
    action VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    trace_id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NULL,
    detail_json JSON NULL,
    created_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    KEY idx_judging_audit_aggregate (aggregate_type, aggregate_id, created_at, id),
    KEY idx_judging_audit_actor (actor_user_id, created_at, id),
    CONSTRAINT ck_judging_audit_aggregate CHECK (aggregate_type IN ('ENVIRONMENT', 'DEPLOYMENT', 'CALIBRATION', 'TASK')),
    CONSTRAINT ck_judging_audit_detail CHECK (detail_json IS NULL OR JSON_TYPE(detail_json) = 'OBJECT')
) ENGINE = InnoDB;
